version: '3.9'

services:
  db:
    image: postgres:16.0-bullseye
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - pmo
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - '8090:8090'
    networks:
      - pmo
    depends_on:
      - db
    command: start-dev --import-realm --http-port=8090
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
  app:
    container_name: tracehub-pmo
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
      - keycloak
    networks:
      - pmo
    env_file:
      - ./docker.env

volumes:
  pgdata:
    driver: local

networks:
  pmo:
    driver: bridge