---
name: reports-check
on:
  issues:
    types: [opened]
jobs:
  check:
    permissions: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: tracehubpm/reports-check-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deepinfra_token: ${{ secrets.DEEPINFRA_TOKEN }}
